### ISSUE TITLE
A crash in ForgeCraft 1.6.20

### ISSUE THREAD

**Issue by Reshirem** [kitsushadow/forgecraft#59]
when i remove a empty crucible in a burning forge,game crash

Description: Rendering item

java.lang.NullPointerException
    at nmd.primal.forgecraft.items.SlottedTongs$1.apply(SlottedTongs.java:81)
    at net.minecraft.client.renderer.block.model.ItemOverride.matchesItemStack(SourceFile:39)
    at net.minecraft.client.renderer.block.model.ItemOverrideList.applyOverride(ItemOverrideList.java:52)
    at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:391)
    at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:550)
    at net.minecraft.client.gui.GuiIngame.renderHotbarItem(GuiIngame.java:1248)
    at net.minecraft.client.gui.GuiIngame.renderHotbar(GuiIngame.java:611)
    at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:346)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:142)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1420)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by kitsushadow** [comment]
Did you place the crucible straight from the creative menu?

**Comment by kitsushadow** [comment]
Im aware of that. It happens when the crucible has no nbt data. placing
something in it will rectify this. also crafting it manually will add the
nbt also

**Comment by Reshirem** [comment]
Will this issue be fixed in the next version?

**Comment by kitsushadow** [comment]
no, its a rare case that only happens in creative or if the crucible isnt
made correctly. i recommend trying the typical place and add items then
pick up the crucible for now. i will look into this in the mean time and
see if there may be a possible solution later.

**Comment by Reshirem** [comment]
I now make such modifications in the src is no problem (although not the best)

                    if (stack.getItem() instanceof SlottedTongs) {
                        if (slotStack.getItem() instanceof ItemNBTCrucible) {
                            /***My added content***/
                            if (slotStack.getTagCompound() != null) {
                            }
                            else
                            {
                                return 0.99f;
                            }
                            /***Render Empty Crucible***/
                            if (slotStack.getSubCompound("BlockEntityTag").getInteger("hot") == 0) {
                                return 0.99f;
                            }
……………………

**Comment by kitsushadow** [comment]
i already have null check code

**Comment by kitsushadow** [comment]
that is not the issue, thats just a bandaid fix. i will resolve this issue at the source of the problem

**Comment by kitsushadow** [comment]
if you wish to discuss more please join our discord

**Comment by kitsushadow** [comment]
This will be fixed with .21
